import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "src/styles/Home.module.css";
import { useLocalStorage } from "src/hooks/useLocaStorage";
import React from "react";
import { CompA } from "src/components/CompA";
import { CompB } from "src/components/CompB";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div
          style={{ display: "flex", justifyContent: "flex-start", gap: "12px" }}
        >
          <CompA />
          <CompB />
        </div>
      </main>
    </>
  );
}
